[package]
name    = "hidio"
version = "0.1.0"
authors = ["Jacob Alexander <haata@kiibohd.com>"]

[dependencies]
hidapi     = "0.3"
log        = "0.3.8"
env_logger = "0.4.3"

# TODO (HaaTa) Make conditional
#xkbcommon = { version = "0.2", features = ["x11"] }

